package com.slf.bo;

import java.math.BigDecimal;

import com.slf.base.BaseObj;

public class LsCz extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.CZID
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private Long czid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.RQ
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String yysbh = "";

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.YYSLSH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String yyslsh = "";

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.SHID
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String ssdq = "";

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.PLWJID
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private Long plwjid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.ZDHM
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String zdhm = "";

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.SJJE
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private BigDecimal sjje;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.BCZSJH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String bczsjh = "";

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.CZJE
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private BigDecimal czje;


    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.CLBZ
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String clbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.CLJG
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String cljg = "";


    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.TDBH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String tdbh = "";


    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_CZ.TIME
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    private String time;


    private String tdzh = "";
    private String tdmm = "";
    

    public String getTdzh() {
		return tdzh;
	}

	public void setTdzh(String tdzh) {
		this.tdzh = tdzh;
	}

	public String getTdmm() {
		return tdmm;
	}

	public void setTdmm(String tdmm) {
		this.tdmm = tdmm;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.CZID
     *
     * @return the value of LS_CZ.CZID
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public Long getCzid() {
        return czid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.CZID
     *
     * @param czid the value for LS_CZ.CZID
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setCzid(Long czid) {
        this.czid = czid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.YYSBH
     *
     * @return the value of LS_CZ.YYSBH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getYysbh() {
        return yysbh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.YYSBH
     *
     * @param yysbh the value for LS_CZ.YYSBH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setYysbh(String yysbh) {
        this.yysbh = yysbh == null ? null : yysbh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.YYSLSH
     *
     * @return the value of LS_CZ.YYSLSH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getYyslsh() {
        return yyslsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.YYSLSH
     *
     * @param yyslsh the value for LS_CZ.YYSLSH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setYyslsh(String yyslsh) {
        this.yyslsh = yyslsh == null ? null : yyslsh.trim();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.SSDQ
     *
     * @return the value of LS_CZ.SSDQ
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getSsdq() {
        return ssdq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.SSDQ
     *
     * @param ssdq the value for LS_CZ.SSDQ
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setSsdq(String ssdq) {
        this.ssdq = ssdq == null ? null : ssdq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.PLWJID
     *
     * @return the value of LS_CZ.PLWJID
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public Long getPlwjid() {
        return plwjid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.PLWJID
     *
     * @param plwjid the value for LS_CZ.PLWJID
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setPlwjid(Long plwjid) {
        this.plwjid = plwjid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.ZDHM
     *
     * @return the value of LS_CZ.ZDHM
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getZdhm() {
        return zdhm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.ZDHM
     *
     * @param zdhm the value for LS_CZ.ZDHM
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setZdhm(String zdhm) {
        this.zdhm = zdhm == null ? null : zdhm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.SJJE
     *
     * @return the value of LS_CZ.SJJE
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public BigDecimal getSjje() {
        return sjje;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.SJJE
     *
     * @param sjje the value for LS_CZ.SJJE
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setSjje(BigDecimal sjje) {
        this.sjje = sjje;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.BCZSJH
     *
     * @return the value of LS_CZ.BCZSJH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getBczsjh() {
        return bczsjh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.BCZSJH
     *
     * @param bczsjh the value for LS_CZ.BCZSJH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setBczsjh(String bczsjh) {
        this.bczsjh = bczsjh == null ? null : bczsjh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.CZJE
     *
     * @return the value of LS_CZ.CZJE
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public BigDecimal getCzje() {
        return czje;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.CZJE
     *
     * @param czje the value for LS_CZ.CZJE
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setCzje(BigDecimal czje) {
        this.czje = czje;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.CLBZ
     *
     * @return the value of LS_CZ.CLBZ
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getClbz() {
        return clbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.CLBZ
     *
     * @param clbz the value for LS_CZ.CLBZ
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setClbz(String clbz) {
        this.clbz = clbz == null ? null : clbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.CLJG
     *
     * @return the value of LS_CZ.CLJG
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getCljg() {
        return cljg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.CLJG
     *
     * @param cljg the value for LS_CZ.CLJG
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setCljg(String cljg) {
        this.cljg = cljg == null ? null : cljg.trim();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.TDBH
     *
     * @return the value of LS_CZ.TDBH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getTdbh() {
        return tdbh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.TDBH
     *
     * @param tdbh the value for LS_CZ.TDBH
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setTdbh(String tdbh) {
        this.tdbh = tdbh == null ? null : tdbh.trim();
    }

   



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_CZ.TIME
     *
     * @return the value of LS_CZ.TIME
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_CZ.TIME
     *
     * @param time the value for LS_CZ.TIME
     *
     * @ibatorgenerated Tue May 20 15:53:12 CST 2014
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }


}